#!/bin/sh

set -e
. /lib/lsb/init-functions

DAEMON=/usr/sbin/usbmuxd
PIDFILE=/var/run/usbmuxd.pid
DAEMON_OPTS=""

start_it_up()
{
  start-stop-daemon --start --background --quiet --make-pidfile  --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
}

shut_it_down()
{
  start-stop-daemon --stop --pidfile $PIDFILE
}


case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart)
    shut_it_down
    start_it_up
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 2
  ;;
esac